### ISSUE TITLE
Update definition

### ISSUE THREAD

**Issue by gordonbondon** [webhookrelay/swagger-webhookrelay#3]
Hi!

Looks like some specs are missing from swagger definition, like updating bucket, rules for outputs, input headers etc.

Will it be possible to update definition with all current features?

I'm working on terraform provider for webhook relay (draft koalificationio/terraform-provider-webhookrelay#1) and it would be great t get all available features in underlying [go client](https://github.com/koalificationio/go-webhookrelay) that is generated from here.

**Comment by rusenask** [comment]
Hi Artem,

Thanks for the PRs and spotting issues! Yes, the rules for outputs are missing API definitions and some other things like inputs and probably bucket settings (ephemeral status). I am going to start updating it now, hopefully it will be finished today or tomorrow :)

**Comment by rusenask** [comment]
Merged updates in https://github.com/webhookrelay/swagger-webhookrelay/pull/4/files. If you encounter any issues, please let me know.

**Comment by gordonbondon** [comment]
Tanks!

One nit: looks like PUT definition for a Bucket is missing (so we can set auth, ephemeral etc.)

**Comment by rusenask** [comment]
added that yesterday I think :)
